#!/bin/bash -e

PAC=naggregator
CMD="$1"
SVC="/etc/init.d/$PAC"

[ ! -x $SVC ] && exit 0

if [ "$CMD" == "upgrade" -o "$CMD" == "remove" ]; then
        # Stop the service
        echo "Stopping $PAC service"
        $SVC stop || true
fi
